### ISSUE TITLE
Human time methods not working correctly.

### ISSUE THREAD

**Issue by joecorkerton** [elm/time#4]
Every time is converted to 18 Jan 1970.

e.g. in elm repl
```
> import Time

-- 1535286333 = current time
> t = Time.millisToPosix 1535286333
> Time.toYear Time.utc t
1970 : Int
```

**Comment by justinmimbs** [comment]
Hi Joe,

It looks like you’re giving `millisToPosix` the Unix time in seconds, but it expects it in milliseconds.

**Comment by joecorkerton** [comment]
Ah yes you are correct, my mistake
